name: Pipeline DevSecOps

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    name: Build & Test (Go)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"

      - name: Run tests
        run: go test -v ./...

      - name: Build binary
        run: go build -v -o webapp .

  security-scan:
    name: SAST (gosec)
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run gosec
        uses: securego/gosec@master
        with:
          args: ./...

  deploy-staging:
    name: Deploy Staging (Linux 1)
    runs-on: ubuntu-latest
    needs: [build-and-test, security-scan]
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Deploy via SSH (docker compose)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 55000
          script: |
            set -e
            if [ ! -d "app" ]; then
              git clone https://github.com/eprohias-coder/fp351R4.git app
            fi
            cd app
            git fetch --all
            git checkout develop
            git pull origin develop
            docker compose up -d --build
            docker ps

  deploy-production:
    name: Deploy Production (Linux 2)
    runs-on: ubuntu-latest
    needs: [build-and-test, security-scan]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy via SSH (docker compose)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 55000
          script: |
            set -e
            if [ ! -d "app" ]; then
              git clone https://github.com/eprohias-coder/fp351R4.git app
            fi
            cd app
            git fetch --all
            git checkout main
            git pull origin main
            docker compose up -d --build
            docker ps
