name: Pipeline DevSecOps

# ¿Cuándo se ejecuta?
# 1. Cuando alguien hace Push a la rama main o develop
# 2. Cuando alguien abre un Pull Request hacia main
on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # TRABAJO 1: CONSTRUIR Y PROBAR (Build & Test)
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: 1. Descargar el código (Checkout)
      uses: actions/checkout@v3

    - name: 2. Instalar Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: 3. Ejecutar Tests (Pruebas)
      run: go test -v ./...

    - name: 4. Construir la aplicación (Build)
      run: go build -v ./...

  # TRABAJO 2: ANÁLISIS DE SEGURIDAD (SAST)
  security-scan:
    runs-on: ubuntu-latest
    needs: build-and-test # Solo se ejecuta si lo anterior salió bien
    steps:
    - name: Descargar código
      uses: actions/checkout@v3

    - name: Ejecutar Gosec (Escáner de Seguridad)
      uses: securego/gosec@master
      with:
        # Escaneamos todo el código
        args: ./...