name: Pipeline DevSecOps

# ¿Cuándo se ejecuta?
# 1. Cuando alguien hace Push a la rama main o develop
# 2. Cuando alguien abre un Pull Request hacia main
on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # TRABAJO 1: CONSTRUIR Y PROBAR (Build & Test)
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: 1. Descargar el código (Checkout)
      uses: actions/checkout@v3

    - name: 2. Instalar Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: 3. Ejecutar Tests (Pruebas)
      run: go test -v ./...

    - name: 4. Construir la aplicación (Build)
      run: go build -v ./...

  # TRABAJO 2: ANÁLISIS DE SEGURIDAD (SAST)
  security-scan:
    runs-on: ubuntu-latest
    needs: build-and-test # Solo se ejecuta si lo anterior salió bien
    steps:
    - name: Descargar código
      uses: actions/checkout@v3

    - name: Ejecutar Gosec (Escáner de Seguridad)
      uses: securego/gosec@master
      with:
        # Escaneamos todo el código
        args: ./...

  # TRABAJO 3: DESPLIEGUE A PRODUCCIÓN (CD)
  deploy:
    needs: [build-and-test, security-scan] # Solo despliega si todo está OK y seguro
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Solo despliega si estamos en la rama main
    steps:
      - name: Desplegar en servidor Linux
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }} # Usa key: ${{ secrets.SERVER_KEY }} si usas clave .pem
          port: 55000
          script: |
            # 1. Comprobamos si es la primera vez (carpeta no existe)
            if [ ! -d "app" ]; then
              echo "La carpeta no existe. Clonando repositorio por primera vez..."
              git clone https://github.com/eprohias-coder/fp351R4.git app
            fi
            
            # 2. Entramos en la carpeta
            cd app
            
            # 3. Descargamos cambios
            git pull origin main
            
            # 4. Compilamos
            /usr/local/go/bin/go build -v -o mi-servidor-web . || go build -v -o mi-servidor-web .
            
            # 5. Reiniciamos la app
            pkill mi-servidor-web || true
            nohup ./mi-servidor-web > server.log 2>&1 &
            
            echo "¡Despliegue completado con éxito!"