name: Pipeline DevSecOps

# ¿Cuándo se ejecuta?
# 1. Cuando alguien hace Push a la rama main o develop
# 2. Cuando alguien abre un Pull Request hacia main
on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # TRABAJO 1: CONSTRUIR Y PROBAR (Build & Test)
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: 1. Descargar el código (Checkout)
      uses: actions/checkout@v3

    - name: 2. Instalar Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: 3. Ejecutar Tests (Pruebas)
      run: go test -v ./...

    - name: 4. Construir la aplicación (Build)
      run: go build -v ./...

  # TRABAJO 2: ANÁLISIS DE SEGURIDAD (SAST)
  security-scan:
    runs-on: ubuntu-latest
    needs: build-and-test # Solo se ejecuta si lo anterior salió bien
    steps:
    - name: Descargar código
      uses: actions/checkout@v3

    - name: Ejecutar Gosec (Escáner de Seguridad)
      uses: securego/gosec@master
      with:
        # Escaneamos todo el código
        args: ./...

  # TRABAJO 3: DESPLIEGUE A PRODUCCIÓN (CD)
  deploy:
    steps:
      - uses: actions/checkout@v3

      - name: Instalar Go en el runner
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Compilar el binario (Linux AMD64)
        run: |
          GOOS=linux GOARCH=amd64 go build -o mi-servidor-web .

      - name: Enviar binario y ejecutar
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 55000
          source: "mi-servidor-web,static/"
          target: "app"

      - name: Arrancar aplicación vía SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 55000
          script: |
            cd app
            chmod +x mi-servidor-web
            pkill mi-servidor-web || true
            nohup ./mi-servidor-web > server.log 2>&1 &